title: Carlos Josué Díaz # your name (or website title) here
logo: "/images/MyLogo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a skilled 3D Environment Artist specializing in creating art brands for objects, buildings, and settings. My abilities lies in 3D modeling and sculpting using Maya and ZBrush, with a focus on texturing based on original designs crafted in Photoshop and Illustrator.  
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/carlos-josué-díaz-464a63197/">View My LinkedIn Profile</a>
  <a href="https://sites.google.com/view/carlosjosuediaz/home/">View My Portfolio</a>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
